# Generated by Django 4.2.3 on 2023-08-05 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orden_de_trabajo', '0006_alter_orden_de_trabajo_descripcion_and_more'),
        ('material', '0006_alter_material_id_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id_otm', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='material.material')),
                ('nro_orden', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orden_de_trabajo.orden_de_trabajo')),
            ],
        ),
    ]
