# Generated by Django 4.2.3 on 2023-08-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_de_trabajo_x_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otm',
            name='cantidad_devolver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otm',
            name='cantidad_utilizada',
            field=models.IntegerField(default=0),
        ),
    ]
