# Generated by Django 4.2.3 on 2023-08-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_de_trabajo_x_material', '0002_otm_cantidad_devolver_otm_cantidad_utilizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otm',
            name='cantidad_devolver',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='otm',
            name='cantidad_utilizada',
            field=models.IntegerField(null=True),
        ),
    ]
