# Generated by Django 4.2.3 on 2023-07-18 11:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material_x_deposito', '0003_alter_material_x_deposito_nombre_mxs'),
        ('empleado', '0005_alter_empleado_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('ID_Transferencias', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(default=datetime.datetime.now)),
                ('Cantidad', models.PositiveIntegerField()),
                ('ID_Empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empleado.empleado')),
                ('ID_MXD_Destino', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Destino', to='material_x_deposito.material_x_deposito')),
                ('ID_MXD_Origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Origen', to='material_x_deposito.material_x_deposito')),
            ],
        ),
    ]
