# Generated by Django 4.2.3 on 2023-07-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(max_length=100)),
                ('codigo_fabricante', models.CharField(max_length=50)),
                ('nro_serial', models.CharField(max_length=50)),
                ('nro_tarjeta', models.CharField(max_length=50)),
            ],
        ),
    ]
