# Generated by Django 4.2.3 on 2023-07-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_material_id_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_material',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
