# Generated by Django 4.2.3 on 2023-07-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_material_id_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='nro_serial',
        ),
        migrations.RemoveField(
            model_name='material',
            name='nro_tarjeta',
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo_fabricante',
            field=models.CharField(max_length=100),
        ),
    ]
