# Generated by Django 4.2.3 on 2023-07-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_material_id_material'),
        ('material', '0004_remove_material_nro_serial_and_more'),
    ]

    operations = [
    ]
