# Generated by Django 4.2.3 on 2023-07-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_merge_20230722_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_material',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
