# Generated by Django 4.2.3 on 2023-07-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposito', '0002_rename_id_empleado_deposito_id_empleado'),
        ('material', '0003_alter_material_id_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_x_Deposito',
            fields=[
                ('ID_MXD', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.PositiveIntegerField()),
                ('Stock_min', models.PositiveIntegerField()),
                ('Stock_max', models.PositiveIntegerField()),
                ('Unidad_medida', models.CharField(max_length=50)),
                ('ID_Deposito', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='deposito.deposito')),
                ('ID_Material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='material.material')),
            ],
        ),
    ]
