# Generated by Django 4.2.3 on 2023-07-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_x_deposito', '0002_material_x_deposito_nombre_mxs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_x_deposito',
            name='Nombre_MXS',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
