# Generated by Django 4.2.3 on 2023-07-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_x_deposito', '0003_alter_material_x_deposito_nombre_mxs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_x_deposito',
            name='Nombre_MXS',
        ),
    ]
