# Generated by Django 4.2.3 on 2023-07-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_x_deposito', '0004_remove_material_x_deposito_nombre_mxs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_x_deposito',
            name='Cantidad',
            field=models.IntegerField(),
        ),
    ]
