# Generated by Django 4.2.3 on 2023-07-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0005_alter_empleado_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id_deposito', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_deposito', models.CharField(max_length=50)),
                ('tipo_deposito', models.CharField(choices=[('Movil', 'Deposito')], max_length=50)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empleado.empleado')),
            ],
        ),
    ]
