# Generated by Django 4.2.3 on 2023-07-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposito',
            old_name='id_empleado',
            new_name='ID_Empleado',
        ),
    ]
