# Generated by Django 4.2.3 on 2023-07-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0002_rename_id_empleado_deposito_id_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='id_deposito',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
