# Generated by Django 4.2.3 on 2023-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposito', '0003_alter_deposito_id_deposito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='tipo_deposito',
            field=models.CharField(choices=[('Movil', 'Deposito general')], max_length=50),
        ),
    ]
