# Generated by Django 4.2.3 on 2023-07-18 08:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0005_alter_empleado_direccion'),
        ('material_x_deposito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('ID_Movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('Concepto', models.CharField(max_length=100)),
                ('Cantidad', models.PositiveIntegerField()),
                ('Fecha', models.DateField(default=datetime.datetime.now)),
                ('Signo', models.IntegerField(choices=[(1, 'Entrada'), (-1, 'Salida')])),
                ('ID_Empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empleado.empleado')),
                ('ID_MXD', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='material_x_deposito.material_x_deposito')),
            ],
        ),
    ]
