# Generated by Django 4.2.3 on 2023-07-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material_x_deposito', '0001_initial'),
        ('empleado', '0005_alter_empleado_direccion'),
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movimientos',
            new_name='Movimiento',
        ),
    ]
