# Generated by Django 4.2.3 on 2023-07-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0002_rename_movimientos_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='Cantidad',
            field=models.IntegerField(),
        ),
    ]
