# Generated by Django 4.2.3 on 2023-07-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('ID_Tarea', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(choices=[('inst', 'Instalación'), ('des', 'Desconección'), ('servTec', 'Servicio Técnico')], max_length=50)),
            ],
        ),
    ]
