# Generated by Django 4.2.3 on 2023-07-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_alter_tarea_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='Tipo',
            new_name='Nombre',
        ),
    ]
