# Generated by Django 4.2.3 on 2023-07-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('ID_Empleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('CI', models.PositiveIntegerField()),
                ('Telefono', models.PositiveIntegerField()),
                ('Direccion', models.CharField(max_length=50)),
                ('Mail', models.CharField(max_length=50)),
                ('Salario', models.DecimalField(decimal_places=2, max_digits=13)),
                ('Estado', models.CharField(choices=[('Activo', 'Inactivo')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
