# Generated by Django 4.2.3 on 2023-07-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('empleado', '0002_empleado_delete_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ID_Cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cargo.cargo'),
        ),
    ]
