# Generated by Django 4.2.3 on 2023-07-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_empleado_id_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Estado',
            field=models.CharField(choices=[('Activo', 'Inactivo')], default='Activo', max_length=50),
        ),
    ]
