# Generated by Django 4.2.3 on 2023-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_alter_empleado_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='Salario',
            field=models.CharField(max_length=50),
        ),
    ]
