# Generated by Django 4.2.3 on 2023-08-01 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_alter_empleado_salario'),
        ('orden_de_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_de_trabajo',
            name='ID_Empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='empleado.empleado'),
        ),
    ]
