# Generated by Django 4.2.3 on 2023-08-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_de_trabajo', '0004_remove_orden_de_trabajo_empleado_ayudante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_de_trabajo',
            name='area_agendada',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden_de_trabajo',
            name='base',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden_de_trabajo',
            name='franquicia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden_de_trabajo',
            name='hoja_de_ruta',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden_de_trabajo',
            name='horario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden_de_trabajo',
            name='plan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
