# Generated by Django 4.2.3 on 2023-08-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_de_trabajo', '0005_orden_de_trabajo_area_agendada_orden_de_trabajo_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_de_trabajo',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orden_de_trabajo',
            name='observacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
